### ISSUE TITLE
A MangaDex user can authenticate

### ISSUE THREAD

**Issue by thedrummeraki** [thedrummeraki/mangadex-client#2]
### Tasks
- [x] Add unauthenticated profile icon button (next to search bar) (#7)
- [x] Implement login modal (#9)
- [x] Persist user session (#10)
- [x] Enable authenticated requests through proxy (`Authorization` headers) (#10)
- [ ] Handle MangaDex API 429 error for authentication
