### ISSUE TITLE
A Guest user registers

### ISSUE THREAD

**Issue by thedrummeraki** [thedrummeraki/mangadex-client#3]
### Description

Any unauthorized user, aka guest user, can browse the site, to the extent that MangaDex allows unauthenticated requests. Those requests include, but are not limited to:
- View manga entries
- View a specific manga entry
- View a manga's chapters
- Read a chapter
- etc.

Registering an account on MangaDex is one of those requests. We have to make clear that the user can register for a MangaDex account and **not** anything else.

### Tasks
- [ ] Implement sign up modal
- [ ] Authenticate the user after sign up is complete
- [ ] Allow user to view account details
